// <auto-generated />
using System;
using AirOps.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirOps.Api.Persistence.Migrations
{
    [DbContext(typeof(AirOpsDbContext))]
    [Migration("20260821001518_InitialOperations")]
    partial class InitialOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirOps.Api.Modules.Flights.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<string>("AircraftRegistration")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("aircraft_registration");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("aircraft_type");

                    b.Property<int>("ConnectingPassengers")
                        .HasColumnType("integer")
                        .HasColumnName("connecting_passengers");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("destination");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("destination_code");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("gate");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("origin");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("origin_code");

                    b.Property<int>("Passengers")
                        .HasColumnType("integer")
                        .HasColumnName("passengers");

                    b.Property<int>("Risk")
                        .HasColumnType("integer")
                        .HasColumnName("risk");

                    b.Property<string>("RiskLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("risk_label");

                    b.Property<DateTimeOffset>("ScheduledArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_arrival");

                    b.Property<DateTimeOffset>("ScheduledDeparture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_departure");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Risk");

                    b.HasIndex("ScheduledDeparture");

                    b.HasIndex("Status");

                    b.ToTable("flights", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
