// <auto-generated />
using System;
using AirOps.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirOps.Api.Persistence.Migrations
{
    [DbContext(typeof(AirOpsDbContext))]
    [Migration("20260821003531_AddAirportAndAircraftOperations")]
    partial class AddAirportAndAircraftOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirOps.Api.Modules.Aircraft.Aircraft", b =>
                {
                    b.Property<string>("Registration")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("registration");

                    b.Property<int>("Cycles")
                        .HasColumnType("integer")
                        .HasColumnName("cycles");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("family");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<decimal>("Hours")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("hours");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("location");

                    b.Property<int>("MaintenanceDue")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_due");

                    b.Property<TimeOnly?>("NextDeparture")
                        .HasColumnType("time without time zone")
                        .HasColumnName("next_departure");

                    b.Property<string>("NextFlight")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("next_flight");

                    b.Property<int>("RangeKilometres")
                        .HasColumnType("integer")
                        .HasColumnName("range_kilometres");

                    b.Property<int>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.Property<int>("Utilization")
                        .HasColumnType("integer")
                        .HasColumnName("utilization");

                    b.HasKey("Registration");

                    b.HasIndex("Family");

                    b.HasIndex("Location");

                    b.HasIndex("Status");

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Airports.Airport", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<int>("Arrivals")
                        .HasColumnType("integer")
                        .HasColumnName("arrivals");

                    b.Property<int>("AtRisk")
                        .HasColumnType("integer")
                        .HasColumnName("at_risk");

                    b.Property<int>("AverageDelay")
                        .HasColumnType("integer")
                        .HasColumnName("average_delay");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<int>("Departures")
                        .HasColumnType("integer")
                        .HasColumnName("departures");

                    b.Property<int>("GatesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("gates_total");

                    b.Property<int>("GatesUsed")
                        .HasColumnType("integer")
                        .HasColumnName("gates_used");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("province");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer")
                        .HasColumnName("temperature");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("timezone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.Property<string>("Weather")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("weather");

                    b.Property<string>("Wind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("wind");

                    b.HasKey("Code");

                    b.HasIndex("Health");

                    b.HasIndex("Risk");

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Flights.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<string>("AircraftRegistration")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("aircraft_registration");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("aircraft_type");

                    b.Property<int>("ConnectingPassengers")
                        .HasColumnType("integer")
                        .HasColumnName("connecting_passengers");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("destination");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("destination_code");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("gate");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("origin");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("origin_code");

                    b.Property<int>("Passengers")
                        .HasColumnType("integer")
                        .HasColumnName("passengers");

                    b.Property<int>("Risk")
                        .HasColumnType("integer")
                        .HasColumnName("risk");

                    b.Property<string>("RiskLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("risk_label");

                    b.Property<DateTimeOffset>("ScheduledArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_arrival");

                    b.Property<DateTimeOffset>("ScheduledDeparture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_departure");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Risk");

                    b.HasIndex("ScheduledDeparture");

                    b.HasIndex("Status");

                    b.ToTable("flights", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Aircraft.Aircraft", b =>
                {
                    b.HasOne("AirOps.Api.Modules.Airports.Airport", null)
                        .WithMany()
                        .HasForeignKey("Location")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
