// <auto-generated />
using System;
using AirOps.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirOps.Api.Persistence.Migrations
{
    [DbContext(typeof(AirOpsDbContext))]
    [Migration("20260825163706_AddDisruptionNetworkAudit")]
    partial class AddDisruptionNetworkAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirOps.Api.Modules.Aircraft.Aircraft", b =>
                {
                    b.Property<string>("Registration")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("registration");

                    b.Property<int>("Cycles")
                        .HasColumnType("integer")
                        .HasColumnName("cycles");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("family");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<decimal>("Hours")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("hours");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("location");

                    b.Property<int>("MaintenanceDue")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_due");

                    b.Property<TimeOnly?>("NextDeparture")
                        .HasColumnType("time without time zone")
                        .HasColumnName("next_departure");

                    b.Property<string>("NextFlight")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("next_flight");

                    b.Property<int>("RangeKilometres")
                        .HasColumnType("integer")
                        .HasColumnName("range_kilometres");

                    b.Property<int>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.Property<int>("Utilization")
                        .HasColumnType("integer")
                        .HasColumnName("utilization");

                    b.HasKey("Registration");

                    b.HasIndex("Family");

                    b.HasIndex("Location");

                    b.HasIndex("Status");

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Airports.Airport", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<int>("Arrivals")
                        .HasColumnType("integer")
                        .HasColumnName("arrivals");

                    b.Property<int>("AtRisk")
                        .HasColumnType("integer")
                        .HasColumnName("at_risk");

                    b.Property<int>("AverageDelay")
                        .HasColumnType("integer")
                        .HasColumnName("average_delay");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<int>("Departures")
                        .HasColumnType("integer")
                        .HasColumnName("departures");

                    b.Property<int>("GatesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("gates_total");

                    b.Property<int>("GatesUsed")
                        .HasColumnType("integer")
                        .HasColumnName("gates_used");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("province");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer")
                        .HasColumnName("temperature");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("timezone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.Property<string>("Weather")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("weather");

                    b.Property<string>("Wind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("wind");

                    b.HasKey("Code");

                    b.HasIndex("Health");

                    b.HasIndex("Risk");

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.CrewDutyImpact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CrewId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crew_id");

                    b.Property<string>("DisruptionId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("disruption_id");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("flight_id");

                    b.Property<int>("LegalLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("legal_limit_minutes");

                    b.Property<int>("ProjectedDutyMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("projected_duty_minutes");

                    b.Property<int>("RemainingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_minutes");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DisruptionId", "Sequence")
                        .IsUnique();

                    b.ToTable("disruption_crew_impacts", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.Disruption", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("id");

                    b.Property<int>("AffectedFlights")
                        .HasColumnType("integer")
                        .HasColumnName("affected_flights");

                    b.Property<int>("AffectedPassengers")
                        .HasColumnType("integer")
                        .HasColumnName("affected_passengers");

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("airport_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CrewAffected")
                        .HasColumnType("integer")
                        .HasColumnName("crew_affected");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("EstimatedCompensation")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_compensation");

                    b.Property<int>("EstimatedOperationalCost")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_operational_cost");

                    b.Property<int>("GateConflicts")
                        .HasColumnType("integer")
                        .HasColumnName("gate_conflicts");

                    b.Property<int>("HotelRooms")
                        .HasColumnType("integer")
                        .HasColumnName("hotel_rooms");

                    b.Property<int>("MealVouchers")
                        .HasColumnType("integer")
                        .HasColumnName("meal_vouchers");

                    b.Property<int>("MissedConnections")
                        .HasColumnType("integer")
                        .HasColumnName("missed_connections");

                    b.Property<string>("PrimaryFlightId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("primary_flight_id");

                    b.Property<int>("RecoveryMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_minutes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AirportCode");

                    b.HasIndex("PrimaryFlightId");

                    b.HasIndex("Severity");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("disruptions", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.DisruptionAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("actor");

                    b.Property<string>("DisruptionId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("disruption_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DisruptionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("disruption_audit_entries", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.GateConflictImpact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Airport")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("airport");

                    b.Property<string>("DisruptionId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("disruption_id");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("gate");

                    b.Property<string>("IncomingFlight")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("incoming_flight");

                    b.Property<string>("OccupyingFlight")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("occupying_flight");

                    b.Property<int>("OverlapMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("overlap_minutes");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("DisruptionId", "Sequence")
                        .IsUnique();

                    b.ToTable("disruption_gate_conflicts", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.ImpactedFlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisruptionId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("disruption_id");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("flight_id");

                    b.Property<int>("MissedConnections")
                        .HasColumnType("integer")
                        .HasColumnName("missed_connections");

                    b.Property<int>("OriginalDelay")
                        .HasColumnType("integer")
                        .HasColumnName("original_delay");

                    b.Property<int>("Passengers")
                        .HasColumnType("integer")
                        .HasColumnName("passengers");

                    b.Property<int>("PropagatedDelay")
                        .HasColumnType("integer")
                        .HasColumnName("propagated_delay");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reason");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("route");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("DisruptionId", "Sequence")
                        .IsUnique();

                    b.ToTable("disruption_flights", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.NetworkMutation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AfterValue")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("after_value");

                    b.Property<Guid>("AuditEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_entry_id");

                    b.Property<string>("BeforeValue")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("before_value");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("field");

                    b.HasKey("Id");

                    b.HasIndex("AuditEntryId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("disruption_network_mutations", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.PassengerConnectionImpact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableConnectionMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("available_connection_minutes");

                    b.Property<string>("ConnectionAirport")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("connection_airport");

                    b.Property<string>("DisruptionId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("disruption_id");

                    b.Property<string>("InboundFlight")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("inbound_flight");

                    b.Property<int>("MinimumConnectionMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_connection_minutes");

                    b.Property<string>("OutboundFlight")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("outbound_flight");

                    b.Property<int>("Passengers")
                        .HasColumnType("integer")
                        .HasColumnName("passengers");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DisruptionId", "Sequence")
                        .IsUnique();

                    b.ToTable("disruption_connections", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Flights.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<string>("AircraftRegistration")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("aircraft_registration");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("aircraft_type");

                    b.Property<int>("ConnectingPassengers")
                        .HasColumnType("integer")
                        .HasColumnName("connecting_passengers");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("destination");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("destination_code");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("gate");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("origin");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("origin_code");

                    b.Property<int>("Passengers")
                        .HasColumnType("integer")
                        .HasColumnName("passengers");

                    b.Property<int>("Risk")
                        .HasColumnType("integer")
                        .HasColumnName("risk");

                    b.Property<string>("RiskLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("risk_label");

                    b.Property<DateTimeOffset>("ScheduledArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_arrival");

                    b.Property<DateTimeOffset>("ScheduledDeparture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_departure");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Risk");

                    b.HasIndex("ScheduledDeparture");

                    b.HasIndex("Status");

                    b.ToTable("flights", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Operations.OperationalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accent");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("detail");

                    b.Property<string>("EntityId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("event_key");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("EventKey")
                        .IsUnique();

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Severity");

                    b.ToTable("operational_events", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Operations.SimulationClockState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CurrentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_time");

                    b.Property<int>("MinutesPerTick")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_per_tick");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("simulation_clock", (string)null);
                });

            modelBuilder.Entity("AirOps.Api.Modules.Aircraft.Aircraft", b =>
                {
                    b.HasOne("AirOps.Api.Modules.Airports.Airport", null)
                        .WithMany()
                        .HasForeignKey("Location")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.CrewDutyImpact", b =>
                {
                    b.HasOne("AirOps.Api.Modules.Disruptions.Disruption", null)
                        .WithMany("CrewDetails")
                        .HasForeignKey("DisruptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.Disruption", b =>
                {
                    b.HasOne("AirOps.Api.Modules.Airports.Airport", null)
                        .WithMany()
                        .HasForeignKey("AirportCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirOps.Api.Modules.Flights.Flight", null)
                        .WithMany()
                        .HasForeignKey("PrimaryFlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.DisruptionAuditEntry", b =>
                {
                    b.HasOne("AirOps.Api.Modules.Disruptions.Disruption", null)
                        .WithMany()
                        .HasForeignKey("DisruptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.GateConflictImpact", b =>
                {
                    b.HasOne("AirOps.Api.Modules.Disruptions.Disruption", null)
                        .WithMany("GateDetails")
                        .HasForeignKey("DisruptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.ImpactedFlight", b =>
                {
                    b.HasOne("AirOps.Api.Modules.Disruptions.Disruption", null)
                        .WithMany("Flights")
                        .HasForeignKey("DisruptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.NetworkMutation", b =>
                {
                    b.HasOne("AirOps.Api.Modules.Disruptions.DisruptionAuditEntry", null)
                        .WithMany("Changes")
                        .HasForeignKey("AuditEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.PassengerConnectionImpact", b =>
                {
                    b.HasOne("AirOps.Api.Modules.Disruptions.Disruption", null)
                        .WithMany("Connections")
                        .HasForeignKey("DisruptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.Disruption", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("CrewDetails");

                    b.Navigation("Flights");

                    b.Navigation("GateDetails");
                });

            modelBuilder.Entity("AirOps.Api.Modules.Disruptions.DisruptionAuditEntry", b =>
                {
                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
